### ISSUE TITLE
Shortcut to comment current selection

### ISSUE THREAD

**Issue by thangngoc89** [thangngoc89/rtop-ui#19]
Should be `Ctrl + /`. not sure how to this, but it's probably somewhere in https://codemirror.net/doc/manual.html#events

**Comment by matthiaskern** [comment]
I've started to look into this. `Ctrl + /` will ring the system bell if the event get's forwarded and i'm not sure there's a way to prevent it with codemirror.

**Comment by thangngoc89** [comment]
@matthiaskern I believe there are some mentions of preventDefault with codeMirror, but I can't remember it

**Comment by thangngoc89** [comment]
Alright, so we have to listen to `keydown` event, we can preventDefault from that
