### ISSUE TITLE
Pressing PageUp and PageDown should move between code block too

### ISSUE THREAD

**Issue by thangngoc89** [thangngoc89/rtop-ui#33]
This should be pretty easy, just need add a new case to this pattern match

https://github.com/thangngoc89/rtop-ui/blob/6395a122980f1504fd51b7f6036a23548b15ca77/client/src_editor/Editor_CodeMirror.re#L132-L134

**Comment by no-stack-dub-sack** [comment]
@thangngoc89 I can take this on as a first issue and will try to familiarize myself with the codebase a bit while I'm at it.

**Comment by thangngoc89** [comment]
@no-stack-dub-sack thank you. please go ahead :)

**Comment by thangngoc89** [comment]
fixed in #48
