### ISSUE TITLE
Add some way to import/export the content

### ISSUE THREAD

**Issue by kyldvs** [thangngoc89/rtop-ui#40]
It would be nice to be able to export the entire contents of the page to some text format that can be re-imported later.

I think ideally it would work like other tools where the content is encoded in the URL, but perhaps this is easier to implement and will make the tool usable more quickly.

**Comment by thangngoc89** [comment]
@kyldvs I'm actually working a server for saving notes. I have been thinking about serailize and deserialize everything too. I'll write a quick issue explaining it later. The possibilities is unlimited

**Comment by kyldvs** [comment]
Awesome. Any sort of way to save the changes will be great. Was thinking it would be cool to have the ability to have gist based notebooks as well so they can be easily shared/discovered/forked/etc.

**Comment by thangngoc89** [comment]
I'm looking for more input in #41

**Comment by kyldvs** [comment]
We can close this in favor of #41 then!
